spring:
  application:
    name: 'ms-notifications'
  profiles:
    include: 'metrics'
eureka:
  client:
    service-url:
      defaultZone: ${EUREKA_URI:http://localhost:8761/eureka}
  instance:
    prefer-ip-address: true
